export enum MESSAGE {
    SUCCESS = 'SUCCESS',
    CREATE = 'CREATE',

    ERR_USER_NOT_FOUNDER = 'ERR_USER_NOT_FOUNDER',
    ERR_USER_NOT_FOUNDER_BY_USERNAME = 'ERR_USER_NOT_FOUNDER_BY_USERNAME',
    ERR_USER_PASSWORD_NOT_MATCH = 'ERR_USER_PASSWORD_NOT_MATCH',
    ERR_USER_EXISTS = 'ERR_USER_EXISTS',

    ERR_ROLE_NOT_FOUNDER = 'ERR_ROLE_NOT_FOUNDER',
    ERR_PEMISSION_NOT_FOUNDER = 'ERR_PEMISSION_NOT_FOUNDER',
    ERR_MENU_NOT_FOUNDER = 'ERR_MENU_NOT_FOUNDER',
    ERR_REFRESHTOKEN_NOT_FOUNDER = 'ERR_REFRESHTOKEN_NOT_FOUNDER',

    ERR_ROLE_NOT_MATCH = 'ERR_ROLE_NOT_MATCH',
    ERR_PERMISSION_NOT_MATCH = 'ERR_PERMISSION_NOT_MATCH',

    ERR_TOKEN_REQUIRED = 'ERR_TOKEN_REQUIRED',
    ERR_TOKEN_INVAILD = 'ERR_TOKEN_INVAILD',
    ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',

    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}