export enum PERMISSION {
    READ_LIST_USER = 'READ_LIST_USER',
    READ_DETAIL_USER = 'READ_DETAIL_USER',
    CREATE_USER = 'CREATE_USER',
    UPDATE_USER = 'UPDATE_USER',
    DELETE_USER = 'DELETE_USER',

    READ_LIST_MENU = 'READ_LIST_MENU',
    READ_DETAIL_MENU = 'READ_DETAIL_MENU',
    CREATE_MENU = 'CREATE_MENU',
    UPDATE_MENU = 'UPDATE_MENU',
    DELETE_MENU = 'DELETE_MENU',

    READ_LIST_PERMISSION = 'READ_LIST_PERMISSION',
    READ_DETAIL_PERMISSION = 'READ_DETAIL_PERMISSION',
    CREATE_PERMISSION = 'CREATE_PERMISSION',
    UPDATE_PERMISSION = 'UPDATE_PERMISSION',
    DELETE_PERMISSION = 'DELETE_PERMISSION',

    READ_LIST_ROLE = 'READ_LIST_ROLE',
    READ_DETAIL_ROLE = 'READ_DETAIL_ROLE',
    CREATE_ROLE = 'CREATE_ROLE',
    UPDATE_ROLE = 'UPDATE_ROLE',
    DELETE_ROLE = 'DELETE_ROLE',

    ASSIGN_PERMISSION_TO_ROLE = 'ASSIGN_PERMISSION_TO_ROLE',
    ASSIGN_ROLE_TO_USER = 'ASSIGN_ROLE_TO_USER',
}