export enum STATUS {
    SUCCESS = 'SUCCESS',
    CREATE = 'CREATE',
    FAILURE = 'FAILURE',
    PENDING = 'PENDING',

    ERR_AUTH_LOGIN = 'ERR_AUTH_LOGIN',
    ERR_FORBIDDEN = 'ERR_FORBIDDEN',
    ERR_NOT_FOUND = 'ERR_NOT_FOUND',
    ERR_VALIDATION = 'ERR_VALIDATION',
    ERR_ACTIVE = 'ERR_ACTIVE',
    ERR_INTERNAL_SERVER = 'ERR_INTERNAL_SERVER',
    ERR_NETWORK_ERROR = 'ERR_NETWORK_ERROR',
    ERR_TOKEN_EXPIRED = 'ERR_TOKEN_EXPIRED',
    ERR_TOKEN_INVALID = 'ERR_TOKEN_INVALID',
    ERR_UNKNOWN_AUTH_ERROR = 'ERR_UNKNOWN_AUTH_ERROR',
    ERR_ROLE_USER = 'ERR_ROLE_USER',
    ERR_PERMISSION_USER = 'ERR_PERMISSION_USER',
    ERR_REFRESH_TOKEN = 'ERR_REFRESH_TOKEN_EXPIRED_OR_INVALID',
    VALIDATION_ERROR = "VALIDATION_ERROR"
}